# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9df44d55d16a9692bf48342b8de003b0ba71987300ab04647d65140421f710811aef4f4e517dfcc7934f057f49f8aa84c134d64bf30d9fc2c85779098acd6417

test:
  secret_key_base: cb572a919c281d73c3aebc2edf19df71cdb10ca66d5b7e02a416dd5696214ab2d42e473d64ff4c846e7c7c06e01b805bde6b8c9ed4fdaa24ad65071359b66226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
